version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      # Default user name und password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      #- KC_LOG_LEVEL=DEBUG
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ../../target/keycloak-ip-authenticator.jar /opt/keycloak/providers/keycloak-ip-authenticator.jar
    restart: always

volumes:
  keycloak-data: